providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.build]
cmd = "npm ci && npx prisma generate"

[phases.start]
cmd = "npm run start:railway"
